using System.Text;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi;
using Microsoft.IdentityModel.Tokens;
using SagraFacile.Application;
using SagraFacile.Application.Interfaces;
using SagraFacile.Infrastructure;
using SagraFacile.Infrastructure.Data;
using SagraFacile.Infrastructure.Identity;
using SagraFacile.Web.Hubs;

var builder = WebApplication.CreateBuilder(args);

builder.AddServiceDefaults();
builder.Services.AddProblemDetails();
builder.Services.AddOpenApi(options =>
{
    options.CreateSchemaReferenceId = type =>
    {
        var defaultReferenceId = Microsoft.AspNetCore.OpenApi.OpenApiOptions.CreateDefaultSchemaReferenceId(type);
        var schemaType = Nullable.GetUnderlyingType(type.Type) ?? type.Type;
        return defaultReferenceId is null
            ? null
            : schemaType.FullName?.Replace("+", ".", StringComparison.Ordinal) ?? defaultReferenceId;
    };

    options.AddOperationTransformer((operation, context, _) =>
    {
        var metadata = context.Description.ActionDescriptor.EndpointMetadata;
        var isAnonymous = metadata.OfType<IAllowAnonymous>().Any();
        var requiresAuthorization = metadata.OfType<IAuthorizeData>().Any();

        if (!isAnonymous && requiresAuthorization)
        {
            operation.Security ??= [];
            operation.Security.Add(new OpenApiSecurityRequirement
            {
                [new OpenApiSecuritySchemeReference("Bearer", context.Document)] = []
            });
        }

        return Task.CompletedTask;
    });

    options.AddDocumentTransformer((document, _, _) =>
    {
        document.Components ??= new OpenApiComponents();
        document.Components.SecuritySchemes ??= new Dictionary<string, IOpenApiSecurityScheme>();
        document.Components.SecuritySchemes["Bearer"] = new OpenApiSecurityScheme
        {
            Type = SecuritySchemeType.Http,
            Scheme = "bearer",
            BearerFormat = "JWT"
        };
        return Task.CompletedTask;
    });
});

builder.Services.AddSignalR();
builder.Services.AddSingleton<ReservationNotificationChannel>();
builder.Services.AddScoped<IReservationNotifier, SignalRReservationNotifier>();
builder.Services.AddHostedService<ReservationNotificationDispatcher>();

var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
                       ?? "Host=localhost;Port=5432;Database=sagrafacile;Username=postgres;Password=postgres";

builder.Services.AddInfrastructureServices(connectionString);
builder.Services.AddApplicationServices();

var jwtKey = builder.Configuration["Jwt:Key"];
var jwtKeyAutoGenerated = false;
if (string.IsNullOrWhiteSpace(jwtKey))
{
    // No key configured: auto-generate a random one so the app starts without manual setup.
    // Useful for LAN/offline deployments where a stable key is not critical.
    // WARNING: every restart invalidates all existing sessions.
    // Set Jwt:Key in configuration or environment variables for stable sessions.
    jwtKey = Convert.ToBase64String(System.Security.Cryptography.RandomNumberGenerator.GetBytes(32));
    jwtKeyAutoGenerated = true;
}

builder.Services.AddAuthentication(options =>
    {
        options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
        options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
    })
    .AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, options =>
    {
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidateAudience = true,
            ValidateLifetime = true,
            ValidateIssuerSigningKey = true,
            ValidIssuer = builder.Configuration["Jwt:Issuer"] ?? "SagraFacile",
            ValidAudience = builder.Configuration["Jwt:Audience"] ?? "SagraFacile",
            IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(jwtKey))
        };

        options.Events = new JwtBearerEvents
        {
            OnMessageReceived = context =>
            {
                var accessToken = context.Request.Query["access_token"];
                var path = context.HttpContext.Request.Path;
                if (!string.IsNullOrEmpty(accessToken) &&
                    path.StartsWithSegments("/hubs/reservations"))
                {
                    context.Token = accessToken;
                }

                return Task.CompletedTask;
            }
        };
    });

builder.Services.AddAuthorizationBuilder()
    .AddPolicy("AdminOnly", policy => policy.RequireRole("Admin"))
    .AddPolicy("AdminOrSupervisore", policy => policy.RequireRole("Admin", "Supervisore"))
    .AddPolicy("Cassiere", policy => policy.RequireRole("Admin", "Supervisore", "Cassiere"))
    .AddPolicy("Cucina", policy => policy.RequireRole("Admin", "Supervisore", "Cucina"));

builder.Services.AddControllers()
    .AddJsonOptions(opts =>
{
    opts.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
});

/*builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(p =>
    {
        p.AllowAnyHeader()
            .AllowAnyMethod()
            .AllowAnyOrigin()
            .SetIsOriginAllowedToAllowWildcardSubdomains()
            .SetIsOriginAllowed(_ => true);
    });
    options.AddPolicy("SignalRPolicy", policy =>
    {
        policy.AllowAnyHeader()
            .AllowAnyMethod()
            .AllowAnyOrigin()
            .SetIsOriginAllowed(_ => true)
            .AllowCredentials();
    });
});*/


var app = builder.Build();

app.MapDefaultEndpoints();

if (jwtKeyAutoGenerated)
{
    var startupLogger = app.Services.GetRequiredService<ILogger<Program>>();
    startupLogger.LogWarning(
        "Jwt:Key is not configured. A random key was auto-generated for this session. " +
        "All authentication tokens will be invalidated on every restart. " +
        "Set Jwt:Key in configuration or the Jwt__Key environment variable for stable sessions.");
}

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
    db.Database.Migrate();
    await DataSeeder.SeedAsync(scope.ServiceProvider);
}

// AllowHttp=true disables HTTPS redirect and HSTS for HTTP-only LAN/offline deployments.

if (!app.Environment.IsDevelopment())
{
    app.UseHsts();
}

if (app.Environment.IsDevelopment())
    app.MapOpenApi();

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();
app.MapHub<ReservationHub>("/hubs/reservations");

app.Run();