version = 1

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["browser"]

[[analyzers]]
name = "html"
enabled = true

[[analyzers]]
name = "css"
enabled = true

[[transformers]]
name = "dotnet-format"
enabled = true

[[transformers]]
name = "prettier"
enabled = true
